### ISSUE TITLE
续期以及重新添加证书报错

### ISSUE THREAD

**Issue by hansonhantong** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#58]
2019-12-15 17:00:33,201:WARNING:certbot._internal.auth_handler:Challenge failed for domain b.xx.cn
2019-12-15 17:00:33,201:WARNING:certbot._internal.auth_handler:Challenge failed for domain c.xx.cn
2019-12-15 17:00:33,201:WARNING:certbot._internal.auth_handler:Challenge failed for domain p.xx.cn
2019-12-15 17:00:33,202:WARNING:certbot._internal.auth_handler:Challenge failed for domain xx.cn

2019-12-15 17:00:33,203:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
AuthorizationError: Some challenges have failed.

**Comment by hansonhantong** [comment]
已解决，阿里key和秘钥不对导致的
