### ISSUE TITLE
dry-run时出现错误

### ISSUE THREAD

**Issue by dannyxu2015** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#59]
我在centos7阿里云服务器上运行dry-run，结果出错，请看看是什么问题（域名的challenges成功了的）：
这是/var/log/letsencrypt/letsencrypt.log日志中的部分：
```
2019-12-19 14:16:22,820:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/cert/fa19e62fe52dfaf28e0520a261332d43e622 HTTP/1.1" 415 168
2019-12-19 14:16:22,821:DEBUG:acme.client:Received response:
HTTP 415
content-length: 168
server: nginx
connection: keep-alive
link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
cache-control: public, max-age=0, no-cache
date: Thu, 19 Dec 2019 06:16:22 GMT
content-type: application/problem+json
replay-nonce: 0001tiiCUTG3mNNunvy9qy2bCAOpQ_d-Ysz1iNbXExa6IE8

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Invalid Content-Type header on POST. Content-Type must be \"application/jose+json\"",
  "status": 415
}
2019-12-19 14:16:22,821:DEBUG:acme.client:Error during a POST-as-GET request, your ACME CA may not support it:
urn:ietf:params:acme:error:malformed :: The request message was malformed :: Invalid Content-Type header on POST. Content-Type must be "application/jose+json"
2019-12-19 14:16:22,821:DEBUG:acme.client:Retrying request with GET.
2019-12-19 14:16:22,821:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa19e62fe52dfaf28e0520a261332d43e622.
2019-12-19 14:16:23,029:DEBUG:requests.packages.urllib3.connectionpool:"GET /acme/cert/fa19e62fe52dfaf28e0520a261332d43e622 HTTP/1.1" 405 103
2019-12-19 14:16:23,030:DEBUG:acme.client:Received response:
HTTP 405
content-length: 103
server: nginx
connection: keep-alive
link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
cache-control: public, max-age=0, no-cache
date: Thu, 19 Dec 2019 06:16:22 GMT
content-type: application/problem+json

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Method not allowed",
  "status": 405
}
2019-12-19 14:16:23,030:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 369, in obtain_certificate
    cert, chain = self.obtain_certificate_from_csr(csr, orderr)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 301, in obtain_certificate_from_csr
    orderr = self.acme.finalize_order(orderr, deadline)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 908, in finalize_order
    return self.client.finalize_order(orderr, deadline)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 743, in finalize_order
    content_type=DER_CONTENT_TYPE).text
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 791, in _post_as_get
    return self.net.get(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 1152, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 1054, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Method not allowed
2019-12-19 14:16:23,052:ERROR:certbot.log:An unexpected error occurred:
2019-12-19 14:16:23,052:ERROR:certbot.log:The request message was malformed :: Method not allowed
```

**Comment by dannyxu2015** [comment]
执行certbot dry-run后的命令行输出是这样的：
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
Cert not due for renewal, but simulating renewal for dry run
Renewing an existing certificate
An unexpected error occurred:
The request message was malformed :: Method not allowed
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by dannyxu2015** [comment]
已解决！更新python-acme即可：
```
yum upgrade python-acme
```
