### ISSUE TITLE
renew失败了

### ISSUE THREAD

**Issue by test3207** [ywdblog/certbot-letencrypt-wildcardcertificates-alydns-au#67]
使用阿里云，san证书，php和python都失败了，应该不是阿里ak的问题，revoke后直接重新签发是可行的；
看起来似乎是调用acme的api时的ak有问题；
我晚点也会自己找一下原因；谢谢；
以下是python下的错误栈：
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/error_handler.py", line 125, in _call_registered
    self.funcs[-1]()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 243, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/plugins/manual.py", line 176, in cleanup
    env = self.env.pop(achall)
KeyError: KeyAuthorizationAnnotatedChallenge(challb=ChallengeBody(chall=DNS01(token='\x0b\x9ca\xfc\xd1\xc9a\xb1\x1dt\xf5\x0eb%\x96\x91UPv\xe1?\x95\xb1B\x11h\x99+9\xc2+\x9b'), status=Status(pending), uri=u'https://acme-v02.api.letsencrypt.org/acme/chall-v3/2754052309/oQssLA', validated=None, _url=u'https://acme-v02.api.letsencrypt.org/acme/chall-v3/2754052309/oQssLA', error=None), domain=u'test3207.com', account_key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey object at 0x7f3dc09f9850>)>))
Attempting to renew cert (test3207.com) from /etc/letsencrypt/renewal/test3207.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
NOTE: The IP of this machine will be publicly logged as having requested this certificate. If you're running certbot in manual mode on a machine that is not your server, please ensure you're okay with that.

**Comment by dennisit** [comment]
the same as you

**Comment by test3207** [comment]
> the same as you

i use acme.sh now XD

sry won't help u with this issue
